"""PuLP interface, both directions.

- :func:`from_pulp` reads a built ``pulp.LpProblem`` into a canonical
  :class:`~lp2graph.core.model.Formulation`, coefficient-faithfully.
- :func:`to_pulp` builds a live, solvable ``pulp.LpProblem`` (this is a
  thin convenience over :func:`lp2graph.solve.grounder.build_problem`).
- :func:`to_pulp_code` emits a standalone, runnable PuLP script.
"""

from __future__ import annotations

from typing import Any

from lp2graph.core.model import Formulation
from lp2graph.interop._grounded import (
    GroundedVar,
    format_number,
    ground,
    grounded_from_pulp,
    py_linexpr,
    to_formulation,
)
from lp2graph.solve.instance import Instance

__all__ = ["from_pulp", "to_pulp", "to_pulp_code"]


def from_pulp(problem: Any) -> Formulation:
    """Read a built ``pulp.LpProblem`` into a flat canonical formulation."""
    return to_formulation(grounded_from_pulp(problem), source="PuLP")


def to_pulp(f: Formulation, instance: Instance | None = None) -> Any:
    """Build a live ``pulp.LpProblem`` from ``f`` (solve with ``prob.solve()``)."""
    from lp2graph.solve.grounder import build_problem

    prob, _ = build_problem(f, instance or Instance(cardinalities={}))
    return prob


def to_pulp_code(f: Formulation, instance: Instance | None = None) -> str:
    """Emit a standalone, runnable PuLP script for ``f``."""
    gm = ground(f, instance)
    sense = "pulp.LpMaximize" if gm.sense == "max" else "pulp.LpMinimize"
    out: list[str] = [
        f'"""Auto-generated by lp2graph interop: model {gm.id}."""',
        "",
        "import pulp",
        "",
        "",
        "def build_problem():",
        f"    prob = pulp.LpProblem({gm.id!r}, {sense})",
        "    v = {}",
    ]
    for v in gm.variables:
        out.append(f"    v[{v.name!r}] = pulp.LpVariable({v.name!r}{_var_args(v)})")
    obj = py_linexpr(gm.objective, gm.objective_constant)
    out.append(f'    prob += {obj}, "objective"')
    cmp_ = {"le": "<=", "ge": ">=", "eq": "=="}
    for c in gm.constraints:
        out.append(
            f"    prob += {py_linexpr(c.terms, 0.0)} {cmp_[c.comparator]} "
            f"{format_number(c.rhs)}, {c.name!r}"
        )
    out += [
        "    return prob",
        "",
        "",
        'if __name__ == "__main__":',
        "    prob = build_problem()",
        "    prob.solve(pulp.PULP_CBC_CMD(msg=False))",
        '    print("status =", pulp.LpStatus[prob.status])',
        '    print("objective =", pulp.value(prob.objective))',
        "    for var in prob.variables():",
        '        print(var.name, "=", var.value())',
        "",
    ]
    return "\n".join(out)


def _var_args(v: GroundedVar) -> str:
    if v.domain == "binary":
        return ', cat="Binary"'
    args = []
    lo = 0.0 if v.domain == "non_negative" and v.lower is None else v.lower
    if lo is not None:
        args.append(f"lowBound={format_number(lo)}")
    if v.upper is not None:
        args.append(f"upBound={format_number(v.upper)}")
    if v.domain == "integer":
        args.append('cat="Integer"')
    return (", " + ", ".join(args)) if args else ""
